
package View.Cliente;
import Model.Bean.Servicos;
import Model.Bean.Status;
import Model.DAO.ServicoDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class View_Servicos extends javax.swing.JInternalFrame {
    
    public View_Servicos() {
        
        initComponents();
    }
    
    /*Ao selecionar um rádio vai abrir a imagem do animal*/
    public void imagemIconGato(){
        ImageIcon img = new ImageIcon(getClass().getResource("/Imagens/Gato-64.png"));
        ImagemAnimal.setIcon(img);       
    }
    public void imagemIconCachorro(){
        ImageIcon img = new ImageIcon(getClass().getResource("/Imagens/Cachorro-64.png"));
        ImagemAnimal.setIcon(img);       
    }
    public void imagemIconRoedor(){
        ImageIcon img = new ImageIcon(getClass().getResource("/Imagens/Roedor-96.png"));
        ImagemAnimal.setIcon(img);       
    }
    public void imagemIconPassaro(){
        ImageIcon img = new ImageIcon(getClass().getResource("/Imagens/Passaro-96.png"));
        ImagemAnimal.setIcon(img);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel15 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        radioAnimalCachorro = new javax.swing.JRadioButton();
        radioAnimalGato = new javax.swing.JRadioButton();
        radioAnimalRoedor = new javax.swing.JRadioButton();
        radioAnimalAve = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Servicos_ani = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAnimal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtAltura = new javax.swing.JTextField();
        Fem = new javax.swing.JRadioButton();
        Masc = new javax.swing.JRadioButton();
        btLimpar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ImagemAnimal = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Serviços");

        jPanel15.setBackground(new java.awt.Color(51, 153, 255));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(radioAnimalCachorro);
        radioAnimalCachorro.setText("Cachorro");
        radioAnimalCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnimalCachorroActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioAnimalGato);
        radioAnimalGato.setText("Gato");
        radioAnimalGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnimalGatoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioAnimalRoedor);
        radioAnimalRoedor.setText("Roedor");
        radioAnimalRoedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnimalRoedorActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioAnimalAve);
        radioAnimalAve.setText("Ave");
        radioAnimalAve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnimalAveMouseClicked(evt);
            }
        });
        radioAnimalAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnimalAveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAnimalAve)
                    .addComponent(radioAnimalGato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAnimalCachorro)
                    .addComponent(radioAnimalRoedor))
                .addGap(33, 33, 33))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnimalAve)
                    .addComponent(radioAnimalCachorro))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnimalGato)
                    .addComponent(radioAnimalRoedor))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Serviços:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Altura(cm):");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Observações:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Sexo:");

        txtObs.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtObs.setForeground(new java.awt.Color(51, 51, 51));
        txtObs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Nome do animal:");

        txtAnimal.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtAnimal.setForeground(new java.awt.Color(51, 51, 51));
        txtAnimal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtAltura.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtAltura.setForeground(new java.awt.Color(51, 51, 51));
        txtAltura.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonGroup2.add(Fem);
        Fem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fem.setText("Feminino");

        buttonGroup2.add(Masc);
        Masc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masc.setText("Masculino");
        Masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(255, 204, 204));
        btLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btConfirmar.setBackground(new java.awt.Color(204, 255, 204));
        btConfirmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(txtObs)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 188, Short.MAX_VALUE))
                                    .addComponent(jSeparator4)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator5)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(Masc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Fem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(Servicos_ani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txtAnimal)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Servicos_ani, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fem, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(Masc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ImagemAnimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAnimalGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnimalGatoActionPerformed
        imagemIconGato();
        Servicos_ani.removeAllItems();
        Servicos_ani.addItem("Banho e tosa - R$30,00");
        Servicos_ani.addItem("Consulta veterinária - R$150,00");
        Servicos_ani.addItem("Vacinação - R$90,00");
    }//GEN-LAST:event_radioAnimalGatoActionPerformed

    private void radioAnimalAveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnimalAveMouseClicked
        imagemIconPassaro();
        Servicos_ani.removeAllItems();
        Servicos_ani.addItem("Consulta veterinária - R$20,00"); 
        Servicos_ani.addItem("Reparo de bico - R$60,00");
        Servicos_ani.addItem("Vacinação - R$70,00");
    }//GEN-LAST:event_radioAnimalAveMouseClicked

    private void radioAnimalCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnimalCachorroActionPerformed
        imagemIconCachorro();
        Servicos_ani.removeAllItems();
        Servicos_ani.addItem("Banho e tosa - R$30,00");
        Servicos_ani.addItem("Consulta veterinária - R$160,00");
        Servicos_ani.addItem("Vacinação - R$100,00");
    }//GEN-LAST:event_radioAnimalCachorroActionPerformed

    private void radioAnimalRoedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnimalRoedorActionPerformed
        imagemIconRoedor();
        Servicos_ani.removeAllItems();
        Servicos_ani.addItem("Consulta veterinária - R$100,00");
        Servicos_ani.addItem("Tratamento anti-estress - R$170,00");
        Servicos_ani.addItem("Vacinação - R$130,00");
    }//GEN-LAST:event_radioAnimalRoedorActionPerformed

    private void radioAnimalAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnimalAveActionPerformed
        
    }//GEN-LAST:event_radioAnimalAveActionPerformed

    private void MascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MascActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed

        Servicos_ani.setSelectedItem(null);
        buttonGroup1.clearSelection();//Desmarca a especie
        buttonGroup2.clearSelection();//Desmarca o sexo
        txtAltura.setText("");
        txtAnimal.setText("");
        txtObs.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        /*Banco de dados*/
        Servicos nvserv = new Servicos();
        ServicoDAO dao = new ServicoDAO();
        /*Banco de dados*/
       
        
        
        String Nome = txtAnimal.getText();/*Global: Pega o nome do animal*/
        String Especie = null;/*Variável global*/   
        int Tservicos = 0;/*Status-Global: inicia o total de serviços*/
        int LucroServ = 0;/*Status-Global: mostra o lucro de cada serviço*/     
        double ValorServico = 0;/*Variável global*/
        String Servico = null;/*Variável global*/
        
        if(radioAnimalAve.isSelected()){/*Se o animal for uma ave*/
            Especie = radioAnimalAve.getText();  
            if(Servicos_ani.getSelectedIndex()==0){
                Servico="Consulta veterinária";
                ValorServico = 20;  
                
                
                
            }
            else if(Servicos_ani.getSelectedIndex()==1){
                Servico="Reparo de bico";
                ValorServico = 60;  
                                  
                
            }
            else{
                Servico="Vacinação";
                ValorServico = 70;    
                ;                    
                
            }
        }
        else if(radioAnimalGato.isSelected()){/*Se o animal for um gato*/
            Especie = radioAnimalGato.getText(); 
            if(Servicos_ani.getSelectedIndex()==0){
               Servico="Banho e tosa";
               ValorServico = 20;
                         
               
            }
            else if(Servicos_ani.getSelectedIndex()==1){
                Servico="Consulta veterinária";
                ValorServico = 150;
                               
                
            }
            else{
                Servico="Vacinação";
                ValorServico = 90;
                                 
                
            }
        }
        else if(radioAnimalCachorro.isSelected()){/*Se o animal for um cachorro*/
            Especie = radioAnimalCachorro.getText(); 
            if(Servicos_ani.getSelectedIndex()==0){
                Servico="Banho e tosa";
                ValorServico = 30;
                                  
                
            }
            else if(Servicos_ani.getSelectedIndex()==1){
               Servico="Consulta veterinária";
               ValorServico = 160;
                                  
               
            }
            else{
                Servico="Vacinação";
                ValorServico = 100;
                                
                
            }
        }
        else{/*Se o animal for um roedor*/
           Especie = radioAnimalRoedor.getText();
           if(Servicos_ani.getSelectedIndex()==0){
               Servico="Consulta veterinária";
               ValorServico = 100;
                               
               
            }
            else if(Servicos_ani.getSelectedIndex()==1){
               Servico="Tratamento anti-estress";
                ValorServico = 170;
                          
               
            }
            else{
                Servico="Vacinação";
                ValorServico = 130;
                                
                
            }
        }
        
        //Altura
        String Altura = txtAltura.getText();
        //Sexo
        String Sexo = null;
        if(Masc.isSelected()){
            Sexo = Masc.getText();
        }
        else if(Fem.isSelected()){
            Sexo = Fem.getText();
        }
        String Serv = (String) Servicos_ani.getSelectedItem();
        String Obs = txtObs.getText();
               
        if((Altura.equals(""))||(Nome.equals(""))||(Obs.equals(""))){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos requisitados.");        
        }
        else{          
            nvserv.setNome(Nome);
            nvserv.setEspecie(Especie);
            nvserv.setAltura(Altura);
            nvserv.setSexo(Sexo);//Alterei
            nvserv.setServico(Servico);
            nvserv.setObs(Obs);
            nvserv.setValorserv(ValorServico);                    
            dao.create(nvserv);
            
            /*Adicona +1 no total de servicos*/
                               
            
  
            JOptionPane.showMessageDialog(this, "Aguarde até o nome do seu animal ser chamado! ", "PetMania informa...",JOptionPane.INFORMATION_MESSAGE);
        
        /*if(Masc.isSelected()){
            String sexo = Masc.getText();
            JOptionPane.showMessageDialog(null,"Você selecionou: "+sexo);       
        }else{
            String sexo = Fem.getText();
            JOptionPane.showMessageDialog(null,"Você selecionou: "+sexo);
        }
        
        String servico = (String)Servicos_ani.getSelectedItem();
        
        JOptionPane.showMessageDialog(null,"Você selecionou: "+servico);
        }*/
        
}
        
    }//GEN-LAST:event_btConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Fem;
    private javax.swing.JLabel ImagemAnimal;
    private javax.swing.JRadioButton Masc;
    private javax.swing.JComboBox<String> Servicos_ani;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JRadioButton radioAnimalAve;
    private javax.swing.JRadioButton radioAnimalCachorro;
    private javax.swing.JRadioButton radioAnimalGato;
    private javax.swing.JRadioButton radioAnimalRoedor;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAnimal;
    private javax.swing.JTextField txtObs;
    // End of variables declaration//GEN-END:variables
  
}
